// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@gamefeel.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "security": [
                    {
                        "PlayFabToken": []
                    }
                ],
                "description": "Authenticate user with PlayFab session token and get JWT for API access",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Login with PlayFab",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PlayFab session token",
                        "name": "X-PlayFab-SessionToken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Login request with PlayFab ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful login with JWT token",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.AuthResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/models.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Invalid PlayFab token",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/models.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/models.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/levels/complete": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Submit level completion with anti-cheat validation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Levels"
                ],
                "summary": "Complete a level",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Level completion data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LevelCompletionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Level completed successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.LevelCompletionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request or cheating detected",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/models.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/models.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/models.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/talents": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve all talents and their levels for the authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Talents"
                ],
                "summary": "Get user talents",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User talents retrieved successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.UserTalent"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/models.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/models.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/talents/upgrade": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Upgrade a talent using gold currency",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Talents"
                ],
                "summary": "Upgrade a talent",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Talent upgrade request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TalentUpgradeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Talent upgraded successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.TalentUpgradeResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request, insufficient gold, or max level",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/models.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/models.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/models.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/models.APIError"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.AuthRequest": {
            "type": "object",
            "required": [
                "playfabId"
            ],
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "playfabId": {
                    "type": "string"
                }
            }
        },
        "models.AuthResponse": {
            "type": "object",
            "properties": {
                "expiresIn": {
                    "description": "seconds",
                    "type": "integer"
                },
                "jwt": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "models.LevelCompletionRequest": {
            "type": "object",
            "required": [
                "finalHp",
                "levelId",
                "mapId",
                "timeSeconds"
            ],
            "properties": {
                "counterCount": {
                    "type": "integer",
                    "minimum": 0
                },
                "dashCount": {
                    "type": "integer",
                    "minimum": 0
                },
                "finalHp": {
                    "type": "number",
                    "minimum": 0
                },
                "levelId": {
                    "type": "string"
                },
                "mapId": {
                    "type": "string"
                },
                "timeSeconds": {
                    "type": "number"
                },
                "vulnerableKills": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "models.LevelCompletionResponse": {
            "type": "object",
            "properties": {
                "goldEarned": {
                    "type": "integer"
                },
                "isFirstCompletion": {
                    "type": "boolean"
                },
                "mapUnlocked": {
                    "type": "string"
                },
                "newBestTime": {
                    "type": "boolean"
                },
                "newTotalGold": {
                    "type": "integer"
                },
                "newTotalStars": {
                    "type": "integer"
                },
                "nextLevelUnlocked": {
                    "type": "string"
                },
                "starsEarned": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.TalentUpgradeRequest": {
            "type": "object",
            "required": [
                "talentId"
            ],
            "properties": {
                "talentId": {
                    "type": "string"
                }
            }
        },
        "models.TalentUpgradeResponse": {
            "type": "object",
            "properties": {
                "goldSpent": {
                    "type": "integer"
                },
                "newLevel": {
                    "type": "integer"
                },
                "newTotalGold": {
                    "type": "integer"
                },
                "nextLevelCost": {
                    "type": "integer"
                },
                "statBonus": {
                    "description": "e.g., \"+5% HP\", \"+3% Damage\"",
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "talentId": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "banReason": {
                    "type": "string"
                },
                "bannedAt": {
                    "type": "string"
                },
                "createdAt": {
                    "description": "Metadata",
                    "type": "string"
                },
                "deletedAt": {
                    "description": "GDPR",
                    "type": "string"
                },
                "diamonds": {
                    "type": "integer"
                },
                "displayName": {
                    "type": "string"
                },
                "facebookId": {
                    "description": "Social",
                    "type": "string"
                },
                "gold": {
                    "description": "Currency",
                    "type": "integer"
                },
                "googleId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isBanned": {
                    "description": "Flags",
                    "type": "boolean"
                },
                "lastLoginAt": {
                    "type": "string"
                },
                "lastPlayedAt": {
                    "type": "string"
                },
                "maxMapUnlocked": {
                    "description": "Progression",
                    "type": "integer"
                },
                "playfabId": {
                    "type": "string"
                },
                "totalPlayTimeSeconds": {
                    "type": "integer"
                },
                "totalStarsCollected": {
                    "type": "integer"
                }
            }
        },
        "models.UserTalent": {
            "type": "object",
            "properties": {
                "currentLevel": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "talentId": {
                    "type": "string"
                },
                "upgradedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT token format: \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "PlayFabToken": {
            "description": "PlayFab session token for authentication",
            "type": "apiKey",
            "name": "X-PlayFab-SessionToken",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "gamefeel-backend.fly.dev",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "GameFeel Backend API",
	Description:      "Game backend API với PlayFab integration, anti-cheat validation, và talent system",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
